"""SQLAlchemy ORM models for the OT Asset Discovery database schema."""

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    BigInteger,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import ARRAY, CIDR, INET, JSONB, MACADDR, UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.db.session import Base


class Device(Base):
    """Core device inventory table.

    Stores discovered OT devices with their attributes, fingerprint data,
    and risk scoring. Enforces uniqueness on MAC+IP combination and
    constrains risk_score to 0-100.
    """

    __tablename__ = "devices"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    mac_address = Column(MACADDR, nullable=False)
    ip_address = Column(INET, nullable=False)
    vendor = Column(String(128), nullable=True)
    model = Column(String(128), nullable=True)
    firmware_version = Column(String(64), nullable=True)
    device_type = Column(String(50), nullable=True)
    protocols = Column(ARRAY(Text), server_default="{}")
    risk_score = Column(Integer, server_default="0", default=0)
    fingerprint = Column(JSONB, nullable=True)
    first_seen = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    last_seen = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    history = relationship("DeviceHistory", back_populates="device", cascade="all, delete-orphan")
    alerts = relationship("Alert", back_populates="device")
    source_edges = relationship(
        "TopologyEdge", foreign_keys="TopologyEdge.source_device_id", back_populates="source_device", cascade="all, delete-orphan"
    )
    dest_edges = relationship(
        "TopologyEdge", foreign_keys="TopologyEdge.dest_device_id", back_populates="dest_device", cascade="all, delete-orphan"
    )

    __table_args__ = (
        UniqueConstraint("mac_address", "ip_address", name="uq_devices_mac_ip"),
        CheckConstraint("risk_score >= 0 AND risk_score <= 100", name="ck_devices_risk_score"),
    )

    def __repr__(self) -> str:
        return f"<Device(id={self.id}, mac={self.mac_address}, ip={self.ip_address}, vendor={self.vendor})>"


class DeviceHistory(Base):
    """Device attribute change history table.

    Records audit trail of attribute changes for each device,
    storing the field name, old value, new value, and timestamp.
    """

    __tablename__ = "device_history"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    device_id = Column(
        UUID(as_uuid=True),
        ForeignKey("devices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    field_name = Column(String(64), nullable=False)
    old_value = Column(Text, nullable=True)
    new_value = Column(Text, nullable=True)
    changed_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)

    # Relationships
    device = relationship("Device", back_populates="history")

    def __repr__(self) -> str:
        return f"<DeviceHistory(device_id={self.device_id}, field={self.field_name}, changed_at={self.changed_at})>"


class Alert(Base):
    """Alerts table for change detection events.

    Stores alerts generated by the change detector with type, severity,
    associated device, and detailed information. Severity is constrained
    to LOW, MEDIUM, HIGH, CRITICAL.
    """

    __tablename__ = "alerts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    alert_type = Column(String(50), nullable=False, index=True)
    severity = Column(String(10), nullable=False, index=True)
    device_id = Column(
        UUID(as_uuid=True),
        ForeignKey("devices.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    details = Column(JSONB, nullable=False)
    generated_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    acknowledged = Column(Boolean, server_default="false", default=False)

    # Relationships
    device = relationship("Device", back_populates="alerts")

    __table_args__ = (
        CheckConstraint(
            "severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name="ck_alerts_severity",
        ),
    )

    def __repr__(self) -> str:
        return f"<Alert(id={self.id}, type={self.alert_type}, severity={self.severity})>"


class TopologyEdge(Base):
    """Network topology edges table.

    Records observed communication relationships between devices,
    tracking protocol, packet count, and timestamps. Enforces uniqueness
    on (source_device_id, dest_device_id, protocol) triple.
    """

    __tablename__ = "topology_edges"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    source_device_id = Column(
        UUID(as_uuid=True),
        ForeignKey("devices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    dest_device_id = Column(
        UUID(as_uuid=True),
        ForeignKey("devices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    protocol = Column(String(30), nullable=False)
    packet_count = Column(BigInteger, server_default="0", default=0)
    first_seen = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    last_seen = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    source_device = relationship("Device", foreign_keys=[source_device_id], back_populates="source_edges")
    dest_device = relationship("Device", foreign_keys=[dest_device_id], back_populates="dest_edges")

    __table_args__ = (
        UniqueConstraint(
            "source_device_id", "dest_device_id", "protocol",
            name="uq_topology_edges_src_dst_proto",
        ),
    )

    def __repr__(self) -> str:
        return f"<TopologyEdge(src={self.source_device_id}, dst={self.dest_device_id}, proto={self.protocol})>"


class ScanJob(Base):
    """Scan jobs table for scheduled and on-demand scans.

    Stores scan configuration, schedule, status, and result metrics.
    """

    __tablename__ = "scan_jobs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    name = Column(String(128), nullable=False)
    schedule = Column(String(64), nullable=True)
    target_subnet = Column(CIDR, nullable=True)
    active_probing_enabled = Column(Boolean, server_default="false", default=False)
    status = Column(String(20), server_default="'scheduled'", nullable=False, default="scheduled")
    started_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    devices_discovered = Column(Integer, server_default="0", default=0)
    new_devices = Column(Integer, server_default="0", default=0)
    alerts_generated = Column(Integer, server_default="0", default=0)
    failure_reason = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    history = relationship("ScanHistory", back_populates="scan_job", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<ScanJob(id={self.id}, name={self.name}, status={self.status})>"


class ScanHistory(Base):
    """Scan job execution history table.

    Records individual execution results for each scan job run.
    """

    __tablename__ = "scan_history"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    scan_job_id = Column(
        UUID(as_uuid=True),
        ForeignKey("scan_jobs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    status = Column(String(20), nullable=False)
    started_at = Column(DateTime(timezone=True), nullable=False, index=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    devices_discovered = Column(Integer, server_default="0", default=0)
    new_devices = Column(Integer, server_default="0", default=0)
    alerts_generated = Column(Integer, server_default="0", default=0)
    failure_reason = Column(Text, nullable=True)

    # Relationships
    scan_job = relationship("ScanJob", back_populates="history")

    def __repr__(self) -> str:
        return f"<ScanHistory(scan_job_id={self.scan_job_id}, status={self.status}, started_at={self.started_at})>"


class User(Base):
    """Users table for authentication and authorization.

    Stores user credentials and role assignments. Role is constrained
    to 'viewer' or 'admin'.
    """

    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    username = Column(String(64), unique=True, nullable=False)
    password_hash = Column(String(256), nullable=False)
    role = Column(String(20), server_default="'viewer'", nullable=False, default="viewer")
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    last_login = Column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        CheckConstraint("role IN ('viewer', 'admin')", name="ck_users_role"),
    )

    def __repr__(self) -> str:
        return f"<User(id={self.id}, username={self.username}, role={self.role})>"


class AuthAttempt(Base):
    """Authentication attempts table for rate limiting.

    Tracks login attempts per IP address for enforcing rate limits
    on failed authentication.
    """

    __tablename__ = "auth_attempts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    ip_address = Column(INET, nullable=False)
    attempted_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    success = Column(Boolean, server_default="false", nullable=False, default=False)

    __table_args__ = (
        Index("idx_auth_attempts_ip", "ip_address", attempted_at.desc()),
    )

    def __repr__(self) -> str:
        return f"<AuthAttempt(ip={self.ip_address}, at={self.attempted_at}, success={self.success})>"
