"""Pydantic domain models for OT Asset Discovery & Inventory Scanner.

Implements all domain entities with field validations including:
- DeviceFingerprint: Protocol parsing output with schema versioning
- Device: Inventory record with constraints
- Alert: Change detection alert
- TopologyGraph/Node/Edge: Network topology representation
- ScanJobConfig: Scan job configuration
- ProbeTarget/ProbeResult: Active probing entities
- ParseResult: Protocol parser output wrapper

Requirements: 2.8, 4.1, 12.1, 12.4
"""

from datetime import datetime
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field
from typing import Literal


class DeviceFingerprint(BaseModel):
    """Structured output from protocol parsing representing a device's identity.

    Contains all identity fields extracted from OT protocol packets.
    Binary fields are stored as base64-encoded strings.
    Includes a schema_version for forward compatibility (Requirement 12.4).
    """

    schema_version: str = Field(
        default="1.0.0",
        pattern=r"^\d+\.\d+\.\d+$",
        description="Semantic version (MAJOR.MINOR.PATCH) for schema compatibility",
    )
    protocol: Literal["modbus_tcp", "ethernetip", "s7comm", "dnp3"]
    source_address: str
    destination_address: str
    mac_address: Optional[str] = None
    ip_address: Optional[str] = None
    vendor: Optional[str] = Field(None, max_length=128)
    model: Optional[str] = Field(None, max_length=128)
    firmware_version: Optional[str] = Field(None, max_length=64)
    device_type: Optional[Literal["PLC", "RTU", "HMI", "IED"]] = None
    serial_number: Optional[str] = None
    protocol_data: dict = Field(
        default_factory=dict,
        description="Protocol-specific fields stored as JSONB",
    )
    parsing_status: Literal["complete", "partial", "no_identity"] = "complete"
    binary_fields: dict[str, str] = Field(
        default_factory=dict,
        description="Base64-encoded binary field values",
    )


class Device(BaseModel):
    """OT device inventory record.

    Represents a discovered device in the inventory with all attributes.
    Enforces constraints from Requirement 4.1:
    - vendor max 128 chars, model max 128 chars, firmware max 64 chars
    - protocols max 20 entries
    - risk_score 0-100
    """

    id: UUID
    mac_address: str
    ip_address: str
    vendor: Optional[str] = Field(None, max_length=128)
    model: Optional[str] = Field(None, max_length=128)
    firmware_version: Optional[str] = Field(None, max_length=64)
    device_type: Optional[str] = None
    protocols: list[str] = Field(default_factory=list, max_length=20)
    risk_score: int = Field(default=0, ge=0, le=100)
    fingerprint: Optional[DeviceFingerprint] = None
    first_seen: datetime
    last_seen: datetime


class Alert(BaseModel):
    """Change detection alert.

    Generated by the Change Detector when device inventory changes are detected.
    Alert types and severities are constrained to known values.
    """

    id: UUID
    alert_type: Literal[
        "new_device",
        "device_disappeared",
        "firmware_change",
        "new_protocol",
        "risk_score_change",
        "scan_failed",
    ]
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    device_id: Optional[UUID] = None
    details: dict
    generated_at: datetime


class TopologyNode(BaseModel):
    """A node in the network topology graph representing a device."""

    device_id: UUID
    name: Optional[str] = None
    ip_address: str
    device_type: Optional[str] = None


class TopologyEdge(BaseModel):
    """An edge in the network topology graph representing a communication path."""

    source_device_id: UUID
    dest_device_id: UUID
    protocol: str
    packet_count: int = Field(ge=0)
    last_seen: datetime


class TopologyGraph(BaseModel):
    """Network topology representation with nodes and edges.

    Includes a stale flag indicating whether the sniffer is currently running.
    """

    nodes: list[TopologyNode] = Field(default_factory=list)
    edges: list[TopologyEdge] = Field(default_factory=list)
    stale: bool = False
    last_updated: Optional[datetime] = None


class ScanJobConfig(BaseModel):
    """Configuration for creating or updating a scan job.

    The schedule field accepts cron expressions with a minimum interval of 5 minutes.
    """

    name: str = Field(max_length=128)
    schedule: Optional[str] = None  # cron expression
    target_subnet: Optional[str] = None  # CIDR notation
    active_probing_enabled: bool = False


class ProbeTarget(BaseModel):
    """Target specification for active device probing."""

    ip_address: str
    protocol: Literal["modbus_tcp", "ethernetip", "s7comm", "dnp3"]
    port: int = Field(ge=1, le=65535)


class ProbeResult(BaseModel):
    """Result of an active probe attempt against a device."""

    target: ProbeTarget
    status: Literal["success", "timeout", "error"]
    fingerprint: Optional[DeviceFingerprint] = None
    error_code: Optional[str] = None
    elapsed_ms: float = Field(ge=0)


class ParseResult(BaseModel):
    """Output from a protocol parser for a single packet.

    Wraps the parsing outcome including the optional fingerprint,
    parsing status, and any error information.
    """

    fingerprint: Optional[DeviceFingerprint] = None
    parsing_status: Literal["complete", "partial", "no_identity"] = "complete"
    protocol: Literal["modbus_tcp", "ethernetip", "s7comm", "dnp3"]
    source_address: str
    destination_address: str
    error: Optional[str] = None
